# MIT License
#
# Copyright (c) 2021 Ben Challenor
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -g prefix `
bind ` send-prefix

set -g default-terminal "tmux-direct"

if -F "#{==:$COLORTERM,truecolor}" {
  set -sa terminal-overrides ",*:Tc"
}

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g mode-keys vi

set -g status-left "#{?#{client_prefix},#[reverse],}[#{session_name}]#[noreverse] "
set -g status-left-length 16
set -g status-right "%a %b %-d, %H:%M"

set -g pane-border-status top
set -g pane-border-format "#{?#{pane_active},#[underscore],}#{pane_index}:#{pane_current_command}#[align=right]#{pane_current_path}"

set-hook -g after-split-window { select-layout -E }
set-hook -g after-kill-pane { select-layout -E }
set-hook -g pane-exited { select-layout -E }

bind-key -T prefix h if -F "#{pane_at_left}"   { display-message "No such pane" } { select-pane -L }
bind-key -T prefix l if -F "#{pane_at_right}"  { display-message "No such pane" } { select-pane -R }
bind-key -T prefix k if -F "#{pane_at_top}"    { display-message "No such pane" } { select-pane -U }
bind-key -T prefix j if -F "#{pane_at_bottom}" { display-message "No such pane" } { select-pane -D }

bind-key -T prefix H if -F "#{pane_at_left}"   { display-message "No such pane" } { swap-pane -s "{left-of}" }
bind-key -T prefix L if -F "#{pane_at_right}"  { display-message "No such pane" } { swap-pane -s "{right-of}" }
bind-key -T prefix K if -F "#{pane_at_top}"    { display-message "No such pane" } { swap-pane -s "{up-of}" }
bind-key -T prefix J if -F "#{pane_at_bottom}" { display-message "No such pane" } { swap-pane -s "{down-of}" }

bind-key -T prefix Enter split-window -c "#{pane_current_path}" -h

bind-key -T prefix o choose-tree -Zs

bind-key -T prefix n {
  display-menu -x0 -yS \
  -T "New" \
  "Session" s { command-prompt -p "Name for new session:" { new-session -s '%%' } } \
  "Window#[align=right]>" w {
    display-menu -xW -yS \
    -T "New Window" \
    "Before"   i { command-prompt -p "Name for new window:" { new-window -n '%%' -b      } } \
    "After"    a { command-prompt -p "Name for new window:" { new-window -n '%%' -a      } } \
    "At Start" I { command-prompt -p "Name for new window:" { new-window -n '%%' -b -t:^ } } \
    "At End"   A { command-prompt -p "Name for new window:" { new-window -n '%%' -a -t:$ } } \
  } \
  "Pane#[align=right]>" p {
    display-menu -xP -yP \
    -T "New Pane" \
    "Before" i { split-window -c "#{pane_current_path}" -h -b } \
    "After"  a { split-window -c "#{pane_current_path}" -h    } \
    "Above"  O { split-window -c "#{pane_current_path}" -v -b } \
    "Below"  o { split-window -c "#{pane_current_path}" -v    } \
  } \
}
